In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_list

[1, 2, 3]

In [5]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr2 = np.arange(5, 50, 5)

In [10]:
arr2

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
arr2 =arr2.reshape(3, 3)

In [17]:
arr2

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr2[1:, :2]

array([[20, 25],
       [35, 40]])

In [21]:
arr_q2=np.zeros(10)

In [23]:
arr_q2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
arr_q3=np.ones(10)*5

In [25]:
arr_q3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [26]:
arr_q4=np.arange(10, 51, 2)

In [27]:
arr_q4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [28]:
arr_q5=np.arange(0, 9)

In [29]:
arr_q5=arr_q5.reshape(3,3)

In [30]:
arr_q5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr_q6 = np.linspace(0, 1, 20)

In [32]:
arr_q6

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])