# Naive Bayes

It is a classification technique based on Bayes’ Theorem with an assumption of independence among predictors. In simple terms, a Naive Bayes classifier assumes that the presence of a particular feature in a class is unrelated to the presence of any other feature.

For example, a fruit may be considered to be an apple if it is red, round, and about 3 inches in diameter. Even if these features depend on each other or upon the existence of the other features, all of these properties independently contribute to the probability that this fruit is an apple and that is why it is known as ‘Naive’.

Naive Bayes model is easy to build and particularly useful for very large data sets. Along with simplicity, Naive Bayes is known to outperform even highly sophisticated classification methods.

Naive Bayes is a classification algorithm for binary (two-class) and multi-class classification problems. The technique is easiest to understand when described using binary or categorical input values.

It is called naive Bayes because the calculation of the probabilities for each hypothesis are simplified to make their calculation tractable. Rather than attempting to calculate the values of each attribute value P(d1, d2, d3|h), they are assumed to be conditionally independent given the target value and calculated as P(d1|h) * P(d2|H) and so on.

## Bayes' Theorem
Bayes’ Theorem is stated as:

P(h|d) = (P(d|h) * P(h)) / P(d)

Where

###### P(h|d) is the probability of hypothesis h given the data d. This is called the posterior probability.
###### P(d|h) is the probability of data d given that the hypothesis h was true.
###### P(h) is the probability of hypothesis h being true (regardless of the data). This is called the prior probability of h.
###### P(d) is the probability of the data (regardless of the hypothesis).

### Useful Libraries

#### Load Dataset. Use "bank-data.csv"

In [1]:
# import dataset
import pandas as pd
df = pd.read_csv('bank-data.csv')

df = df.replace(['NO'], 0)
df = df.replace(['YES'],1)
df = df.replace(['FEMALE'],0)
df = df.replace(['MALE'],1)
df = df.replace(['INNER_CITY'],1)
df = df.replace(['TOWN'],2)
df = df.replace(['SUBURBAN'],3)
df = df.replace(['RURAL'],4)

df.head() # used to display top 5 rows

id  age  sex  region   income  married  children  car  save_act  \
0  ID12101   48    0       1  17546.0        0         1    0         0   
1  ID12102   40    1       2  30085.1        1         3    1         0   
2  ID12103   51    0       1  16575.4        1         0    1         1   
3  ID12104   23    0       2  20375.4        1         3    0         0   
4  ID12105   57    0       4  50576.3        1         0    0         1   

   current_act  mortgage  pep  
0            0         0    1  
1            1         1    0  
2            1         0    0  
3            1         0    0  
4            0         0    0

#### Preprocess the data

In [2]:
# import library for preprocessing
from sklearn import preprocessing
import numpy as np
x = df.values
min_max_scaler = preprocessing.MinMaxScaler()
print(x)

[['ID12101' 48 0 ... 0 0 1]
 ['ID12102' 40 1 ... 1 1 0]
 ['ID12103' 51 0 ... 1 0 0]
 ...
 ['ID12577' 43 1 ... 1 0 1]
 ['ID12578' 40 1 ... 1 1 0]
 ['ID12579' 47 1 ... 1 1 0]]


In [3]:
# Tranform data using "fit_transform(attribute)" function  
x_scaled = min_max_scaler.fit_transform(x[:,1:])
            
ndf = pd.DataFrame(x_scaled)

ndf

0    1         2         3    4         5    6    7    8    9    10
0    0.612245  0.0  0.000000  0.215634  0.0  0.333333  0.0  0.0  0.0  0.0  1.0
1    0.448980  1.0  0.333333  0.431395  1.0  1.000000  1.0  0.0  1.0  1.0  0.0
2    0.673469  0.0  0.000000  0.198933  1.0  0.000000  1.0  1.0  1.0  0.0  0.0
3    0.102041  0.0  0.333333  0.264320  1.0  1.000000  0.0  0.0  1.0  0.0  0.0
4    0.795918  0.0  1.000000  0.783987  1.0  0.000000  0.0  1.0  0.0  0.0  0.0
..        ...  ...       ...       ...  ...       ...  ...  ...  ...  ...  ...
474  0.265306  0.0  0.333333  0.303943  0.0  0.333333  1.0  1.0  1.0  1.0  1.0
475  0.306122  0.0  0.333333  0.123276  1.0  0.666667  0.0  1.0  1.0  1.0  0.0
476  0.510204  1.0  1.000000  0.362938  0.0  0.333333  0.0  0.0  1.0  0.0  1.0
477  0.448980  1.0  0.000000  0.385495  1.0  0.000000  0.0  1.0  1.0  1.0  0.0
478  0.591837  1.0  0.333333  0.315284  1.0  0.666667  0.0  1.0  1.0  1.0  0.0

[479 rows x 11 columns]

#### Select independent variables and target column

In [4]:
# Select the independent variables and the target attribute
X = ndf[ndf.columns[:-1]] # Selecting the independent variables
Y = ndf[ndf.columns[len(ndf.columns)-1]] # selecting only the target lableled column

#### Import Naive Bayes Classifier library 

In [5]:
# import Classifier library
from sklearn.naive_bayes import GaussianNB

In [6]:
# Call the Classifier
nbc = GaussianNB()

#### Predict the target column and find the perfromance of the model

In [7]:
# Divide the dataset into training and testing partition
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state = 30)

In [8]:
# Print Number of mislabeled points
from sklearn.metrics import accuracy_score
import math
nbc.fit(X_train, Y_train)
predictions = nbc.predict(X_test)
print(accuracy_score(Y_test,predictions))
print(math.ceil((1-accuracy_score(Y_test,predictions))*479*0.3))

0.625
54


### Prediction and Evaluation

In [9]:
# import required libraries
from sklearn.metrics import classification_report,confusion_matrix

In [10]:
# Calculate and print confusion matrix and other performance measures (Refer previous labsheet)
print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.65      0.71      0.68        80
         1.0       0.59      0.52      0.55        64

    accuracy                           0.62       144
   macro avg       0.62      0.61      0.61       144
weighted avg       0.62      0.62      0.62       144

Confusion Matrix
[[57 23]
 [31 33]]

 Accuracy
0.625


#### Q1: Consider "current_act" as an irrelevant attribute. Remove it and find the accuracy of Naive Bayes classifier

In [11]:
# display dataframe first 5 columns
ddf = ndf.drop(columns = 8)
ddf.head()

0    1         2         3    4         5    6    7    9    10
0  0.612245  0.0  0.000000  0.215634  0.0  0.333333  0.0  0.0  0.0  1.0
1  0.448980  1.0  0.333333  0.431395  1.0  1.000000  1.0  0.0  1.0  0.0
2  0.673469  0.0  0.000000  0.198933  1.0  0.000000  1.0  1.0  0.0  0.0
3  0.102041  0.0  0.333333  0.264320  1.0  1.000000  0.0  0.0  0.0  0.0
4  0.795918  0.0  1.000000  0.783987  1.0  0.000000  0.0  1.0  0.0  0.0

In [12]:
# Selecting the independent variables
X = ddf[ddf.columns[:-1]] # Selecting the independent variables

In [13]:
# selecting only the target lableled column
Y = ddf[ddf.columns[len(ddf.columns)-1]] # selecting only the target lableled column

In [14]:
# Apply the classifier and Print Number of mislabeled points
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state = 30)
nbc2 = GaussianNB()
nbc2.fit(X_train, Y_train)
predictions = nbc2.predict(X_test)
print(accuracy_score(Y_test,predictions))
print(math.ceil((1-accuracy_score(Y_test,predictions))*479*0.3))

0.625
54


In [15]:
# Calculate and print confusion matrix and other performance measures
print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.64      0.72      0.68        80
         1.0       0.59      0.50      0.54        64

    accuracy                           0.62       144
   macro avg       0.62      0.61      0.61       144
weighted avg       0.62      0.62      0.62       144

Confusion Matrix
[[58 22]
 [32 32]]

 Accuracy
0.625


#### Q2: Write your observation

there is very little change in the accuracy, proving that current_act was an irrelevant attribute

### Load "car.csv" dataset. 

#### Q3: Apply Naive Bayes classifier on this dataset

In [16]:
# Load the data
df = pd.read_csv('car.csv', header=None)
Y = df[df.columns[len(df.columns)-1]]# selecting only the target lableled column
df = df[df.columns[:-1]]
df = df.replace(['unacc'], 0)
df = df.replace(['acc'],1)
df = df.replace(['good'],2)
df = df.replace(['vgood'],3)
df = df.replace(['small'],0)
df = df.replace(['big'],2)
df = df.replace(['low'],0)
df = df.replace(['med'],1)
df = df.replace(['high'],2)
df = df.replace(['vhigh'],3)
print(df.head())
# shuffle the DataFrame rows 
df = df.sample(frac=1).reset_index(drop=True)
df.head()

   0  1  2  3  4  5
0  3  3  2  2  0  0
1  3  3  2  2  0  1
2  3  3  2  2  0  2
3  3  3  2  2  1  0
4  3  3  2  2  1  1


0  1  2  3  4  5
0  2  3  6  6  1  2
1  0  2  2  2  0  2
2  2  2  4  4  2  1
3  2  3  4  2  0  2
4  0  1  3  6  1  2

In [17]:
# Preprocess and Tranform data using "fit_transform(attribute)" function  
x = df.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)            
df = pd.DataFrame(x_scaled)
df

0         1     2    3    4    5
0     0.666667  1.000000  1.00  1.0  0.5  1.0
1     0.000000  0.666667  0.00  0.0  0.0  1.0
2     0.666667  0.666667  0.50  0.5  1.0  0.5
3     0.666667  1.000000  0.50  0.0  0.0  1.0
4     0.000000  0.333333  0.25  1.0  0.5  1.0
...        ...       ...   ...  ...  ...  ...
1723  0.000000  1.000000  0.00  0.0  1.0  1.0
1724  0.666667  1.000000  0.00  0.5  0.0  0.0
1725  1.000000  0.666667  0.50  1.0  0.0  0.5
1726  0.000000  1.000000  0.50  0.0  0.5  0.0
1727  0.666667  0.666667  0.00  0.0  0.5  0.5

[1728 rows x 6 columns]

In [18]:
# Select the independent variables and the target attribute
X = df # Selecting the independent variables

In [19]:
# Apply the classifier
nbc3 = GaussianNB()

In [20]:
# Divide the dataset into training and testing partition
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state = 30)
# predictions for testing partition
nbc3.fit(X_train, Y_train)
predictions = nbc3.predict(X_test)

In [21]:
# Print Number of mislabeled points
print(accuracy_score(Y_test,predictions))
print(math.ceil((1-accuracy_score(Y_test,predictions))*1728*0.3))

0.7090558766859345
151


In [22]:
# Calculate and print confusion matrix and other performance measures
print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

              precision    recall  f1-score   support

         acc       0.00      0.00      0.00       111
        good       0.00      0.00      0.00        21
       unacc       0.71      1.00      0.83       368
       vgood       0.00      0.00      0.00        19

    accuracy                           0.71       519
   macro avg       0.18      0.25      0.21       519
weighted avg       0.50      0.71      0.59       519

Confusion Matrix
[[  0   0 111   0]
 [  0   0  21   0]
 [  0   0 368   0]
 [  0   0  19   0]]

 Accuracy
0.7090558766859345


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### Q4: Find the correlation between the attributes of the dataset.

In [23]:
# Find the pairwise correlation of attributes and arrange in ascending order
a = df.corr()
maxr = 0
maxc = 0
maxa = 0
for x in range(6):
    a[x][x]=0
for x in range(6):
    for y in range(6):
       if(abs(a[x][y])>maxa):
        maxa = abs(a[x][y])
        maxr = x
        maxc = y

#### Q5: Remove one of the highly correlated attributes and apply Naive Bayes classifier

In [24]:
# Drop highly correlated attribute
df = df.drop(columns = maxc)
X = df

In [25]:
# Apply the classifier
nbc4 = GaussianNB()
# Divide the dataset into training and testing partition
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state = 30)
# predictions for testing partition
nbc4.fit(X_train, Y_train)
predictions = nbc4.predict(X_test)
# Print Number of mislabeled points
print(accuracy_score(Y_test,predictions))
print(math.ceil((1-accuracy_score(Y_test,predictions))*1728*0.3))

0.7090558766859345
151


In [27]:
# Calculate and print confusion matrix and other performance measures
print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

              precision    recall  f1-score   support

         acc       0.00      0.00      0.00       111
        good       0.00      0.00      0.00        21
       unacc       0.71      1.00      0.83       368
       vgood       0.00      0.00      0.00        19

    accuracy                           0.71       519
   macro avg       0.18      0.25      0.21       519
weighted avg       0.50      0.71      0.59       519

Confusion Matrix
[[  0   0 111   0]
 [  0   0  21   0]
 [  0   0 368   0]
 [  0   0  19   0]]

 Accuracy
0.7090558766859345


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### Q6: Write your observation below in the performance of model in Q4 and Q6

There is no change in the accuracy. This is as the classifier is assigning 'unacc' to all values